remote_theme: "mmistakes/minimal-mistakes@4.24.0"
plugins:
  - jekyll-relative-links
  - jekyll-include-cache
relative_links:
  enabled: true
  collections: true
include:
  - README.md
  - Week5.md
name: "Richard Luo"
title_separator: "|"